In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\home\Desktop\ვებიზი\Final Project\1505_0.csv")
df.head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

In [4]:
df.shape

(1573, 43)

In [5]:
df = df.drop(columns=[
    "product_url",
    "product_picture",
    "merchant_profile_picture",
    "merchant_info_subtitle",
    "theme",
    "crawl_month"
])

In [6]:
df.shape

(1573, 37)

In [7]:
df.isnull().sum()

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
product_id                         0
dtype: int64

In [8]:
df[[
"rating_five_count",
"rating_four_count",
"rating_three_count",
"rating_two_count",
"rating_one_count"
]] = df[[
"rating_five_count",
"rating_four_count",
"rating_three_count",
"rating_two_count",
"rating_one_count"
]].fillna(0)

In [9]:
df.isnull().sum()

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                  0
rating_four_count                  0
rating_three_count                 0
rating_two_count                   0
rating_one_count                   0
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
product_id                         0
dtype: int64

In [10]:
df["product_color"] = df["product_color"].fillna("Unknown")

In [11]:
df["product_variation_size_id"] = df["product_variation_size_id"].fillna("Unknown")

In [12]:
df["origin_country"] = df["origin_country"].fillna("Unknown")

In [13]:
df["merchant_name"] = df["merchant_name"].fillna("Unknown")

In [14]:
df["has_urgency"] = df["urgency_text"].notna().astype(int)

In [15]:
df = df.drop(columns=["urgency_text"])

In [16]:
import numpy as np

df["rating_five_count"] = df["rating_five_count"].replace(0, np.nan)
df["rating_four_count"] = df["rating_four_count"].replace(0, np.nan)
df["rating_three_count"] = df["rating_three_count"].replace(0, np.nan)
df["rating_two_count"] = df["rating_two_count"].replace(0, np.nan)
df["rating_one_count"] = df["rating_one_count"].replace(0, np.nan)

In [17]:
df["rating_five_count"] = df["rating_five_count"].fillna(df["rating_five_count"].mode()[0])
df["rating_four_count"] = df["rating_four_count"].fillna(df["rating_four_count"].mode()[0])
df["rating_three_count"] = df["rating_three_count"].fillna(df["rating_three_count"].mode()[0])
df["rating_two_count"] = df["rating_two_count"].fillna(df["rating_two_count"].mode()[0])
df["rating_one_count"] = df["rating_one_count"].fillna(df["rating_one_count"].mode()[0])

In [18]:
df.isnull().sum()

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                  0
rating_four_count                  0
rating_three_count                 0
rating_two_count                   0
rating_one_count                   0
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                      0
product_variation_size_id          0
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
origin_country                     0
merchant_title                     0
merchant_name                      0
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
product_id                         0
has_urgency                        0
dtype: int64

In [19]:
df = df.drop(columns=["has_urgency_banner"])

In [20]:
df.shape

(1573, 36)

In [21]:
df.isnull().sum()

title                           0
title_orig                      0
price                           0
retail_price                    0
currency_buyer                  0
units_sold                      0
uses_ad_boosts                  0
rating                          0
rating_count                    0
rating_five_count               0
rating_four_count               0
rating_three_count              0
rating_two_count                0
rating_one_count                0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
tags                            0
product_color                   0
product_variation_size_id       0
product_variation_inventory     0
shipping_option_name            0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
inventory_total                 0
origin_country                  0
merchant_title                  0
merchant_name                   0
merchant_rating_count           0
merchant_rating                 0
merchant_id                     0
merchant_has_profile_picture    0
product_id                      0
has_urgency                     0
dtype: int64

In [22]:
df = df.drop(columns=["merchant_has_profile_picture"])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   title                        1573 non-null   object
 1   title_orig                   1573 non-null   object
 2   price                        1573 non-null   float64
 3   retail_price                 1573 non-null   int64
 4   currency_buyer               1573 non-null   object
 5   units_sold                   1573 non-null   int64
 6   uses_ad_boosts               1573 non-null   int64
 7   rating                       1573 non-null   float64
 8   rating_count                 1573 non-null   int64
 9   rating_five_count            1573 non-null   float64
 10  rating_four_count            1573 non-null   float64
 11  rating_three_count           1573 non-null   float64
 12  rating_two_count             1573 non-null   float64
 13  rating_one_count             1573 non-null   float64
 14  badges_count                 1573 non-null   int64
 15  badge_local_product          1573 non-null   int64
 16  badge_product_quality        1573 non-null   int64
 17  badge_fast_shipping          1573 non-null   int64
 18  tags                         1573 non-null   object
 19  product_color                1573 non-null   object
 20  product_variation_size_id    1573 non-null   object
 21  product_variation_inventory  1573 non-null   int64
 22  shipping_option_name         1573 non-null   object
 23  shipping_option_price        1573 non-null   int64
 24  shipping_is_express          1573 non-null   int64
 25  countries_shipped_to         1573 non-null   int64
 26  inventory_total              1573 non-null   int64
 27  origin_country               1573 non-null   object
 28  merchant_title               1573 non-null   object
 29  merchant_name                1573 non-null   object
 30  merchant_rating_count        1573 non-null   int64
 31  merchant_rating              1573 non-null   float64
 32  merchant_id                  1573 non-null   object
 33  product_id                   1573 non-null   object
 34  has_urgency                  1573 non-null   int64
dtypes: float64(8), int64(15), object(12)
memory usage: 430.2+ KB

In [24]:
cols = [
    "rating_five_count",
    "rating_four_count",
    "rating_three_count",
    "rating_two_count",
    "rating_one_count"
]

In [25]:
df[cols] = df[cols].astype(int)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   title                        1573 non-null   object
 1   title_orig                   1573 non-null   object
 2   price                        1573 non-null   float64
 3   retail_price                 1573 non-null   int64
 4   currency_buyer               1573 non-null   object
 5   units_sold                   1573 non-null   int64
 6   uses_ad_boosts               1573 non-null   int64
 7   rating                       1573 non-null   float64
 8   rating_count                 1573 non-null   int64
 9   rating_five_count            1573 non-null   int64
 10  rating_four_count            1573 non-null   int64
 11  rating_three_count           1573 non-null   int64
 12  rating_two_count             1573 non-null   int64
 13  rating_one_count             1573 non-null   int64
 14  badges_count                 1573 non-null   int64
 15  badge_local_product          1573 non-null   int64
 16  badge_product_quality        1573 non-null   int64
 17  badge_fast_shipping          1573 non-null   int64
 18  tags                         1573 non-null   object
 19  product_color                1573 non-null   object
 20  product_variation_size_id    1573 non-null   object
 21  product_variation_inventory  1573 non-null   int64
 22  shipping_option_name         1573 non-null   object
 23  shipping_option_price        1573 non-null   int64
 24  shipping_is_express          1573 non-null   int64
 25  countries_shipped_to         1573 non-null   int64
 26  inventory_total              1573 non-null   int64
 27  origin_country               1573 non-null   object
 28  merchant_title               1573 non-null   object
 29  merchant_name                1573 non-null   object
 30  merchant_rating_count        1573 non-null   int64
 31  merchant_rating              1573 non-null   float64
 32  merchant_id                  1573 non-null   object
 33  product_id                   1573 non-null   object
 34  has_urgency                  1573 non-null   int64
dtypes: float64(3), int64(20), object(12)
memory usage: 430.2+ KB

In [27]:
df.duplicated().sum()

np.int64(34)

In [28]:
df = df.drop_duplicates()

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df[['price', 'retail_price', 'units_sold', 'rating']].describe()

             price  retail_price     units_sold       rating
count  1539.000000   1539.000000    1539.000000  1539.000000
mean      8.356452     23.317089    4422.480182     3.822840
std       3.937161     30.309642    9438.316389     0.508619
min       1.000000      1.000000       1.000000     1.000000
25%       5.825000      7.000000     100.000000     3.550000
50%       8.000000     10.000000    1000.000000     3.850000
75%      11.000000     26.000000    5000.000000     4.110000
max      49.000000    252.000000  100000.000000     5.000000

In [31]:
df[df["retail_price"] > 200]

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,countries_shipped_to,inventory_total,origin_country,merchant_title,merchant_name,merchant_rating_count,merchant_rating,merchant_id,product_id,has_urgency
721,Femmes sexy une pièce push-up bikini bandage m...,Sexy Women One-Piece Push Up Bikini Bandage Mo...,11.0,250,EUR,20000,0,3.64,3397,1342,...,47,50,CN,GL,gl,402743,4.156715,53facca81c105e3d5866e212,56975d088b70437255bf8af8,1
1215,Aowofs Salopette d'été en coton pour homme Cam...,Aowofs Men's Summer Cotton Overalls Summer Cam...,13.0,252,EUR,20000,0,3.91,12041,5723,...,35,50,CN,bushangfushi,bushangfushi,45964,4.097119,5756d060b833235cbc250227,576ba1eb7f3351084cd0b578,0
1349,S-5XL Plus La Taille D'été De Mode Femmes Sans...,S-5XL Plus Size Summer Fashion Women Sleeveles...,8.0,252,EUR,1000,1,3.88,161,79,...,41,50,CN,Legeit,legeit,14780,3.950812,56961502ca1588618ca6d5fe,5ae978af2d88f95727d921f2,0

In [32]:
df.dtypes

title                           object
title_orig                      object
price                          float64
retail_price                     int64
currency_buyer                  object
units_sold                       int64
uses_ad_boosts                   int64
rating                         float64
rating_count                     int64
rating_five_count                int64
rating_four_count                int64
rating_three_count               int64
rating_two_count                 int64
rating_one_count                 int64
badges_count                     int64
badge_local_product              int64
badge_product_quality            int64
badge_fast_shipping              int64
tags                            object
product_color                   object
product_variation_size_id       object
product_variation_inventory      int64
shipping_option_name            object
shipping_option_price            int64
shipping_is_express              int64
countries_shipped_to             int64
inventory_total                  int64
origin_country                  object
merchant_title                  object
merchant_name                   object
merchant_rating_count            int64
merchant_rating                float64
merchant_id                     object
product_id                      object
has_urgency                      int64
dtype: object

In [33]:
df["discount"] = df["retail_price"] - df["price"]

In [34]:
df["discount"].describe()

count    1539.000000
mean       14.960637
std        29.349070
min        -7.000000
25%        -1.000000
50%         0.200000
75%        18.000000
max       244.000000
Name: discount, dtype: float64

In [35]:
df[df["discount"] < 0]

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,inventory_total,origin_country,merchant_title,merchant_name,merchant_rating_count,merchant_rating,merchant_id,product_id,has_urgency,discount
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26,...,50,CN,zgrdejia,zgrdejia,568,4.128521,595097d6a26f6e070cb878d1,5e9ae51d43d6a96e303acdb0,1,-2.00
6,Women Fashion Loose Lace Blouse Blouse V Neck ...,Women Fashion Loose Lace Blouse V Neck Bat Sle...,7.00,6,EUR,50000,0,3.84,6742,3172,...,50,CN,Unique Li Fashion Shop,uniquelifashionshopbb657bfe91d211e598c7063a14d...,10194,4.076516,5652f4053a698c76dc9a3f37,5c63a337d5e2ce4bbb3152cf,0,-1.00
7,Robe tunique ample femme Robe d'été Robe en je...,Women's Baggy Tunic Dress Summer Dress Denim D...,12.00,11,EUR,1000,0,3.76,286,120,...,50,CN,So Band,soband,342,3.681287,5d45349676befe65691dcfbb,5e0ae5ebc2efb76ccf0a3391,0,-1.00
10,Femmes Mode Été Lâche Sans Manches Poches Coul...,Women's Fashion Summer Loose Sleeveless Pocket...,5.79,5,EUR,1000,0,3.46,613,245,...,50,CN,mayuhiao,mayuhiao,9470,3.956811,5952a218e81e8a4c30b5bbbc,5cac5af68de7960d89e54fe0,1,-0.79
16,Nouvelle mode d'été pour femmes Robe sans manc...,New Summer Women's Fashion Sleeveless Polka Do...,11.00,10,EUR,10000,0,3.72,2058,840,...,50,CN,2312hangm,2312hangm,6302,3.958426,5b8beef49996c87b299cdbec,5cd3e795ebe403118bbc0f89,0,-1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1559,Tendances vêtements de sport d'été pour hommes...,Trending Summer Sports Wear for Men Casual Two...,16.00,14,EUR,100,1,4.05,82,43,...,50,CN,huangyulanl,huangyulanl,514,4.217899,5b0b907d59206904541886cf,5ea0f2a654446407c111b622,0,-2.00
1564,2018 Femme mode d'été en dentelle Patchwork Pa...,2018 Women fashion Summer Lace Patchwork Tank ...,5.91,5,EUR,1000,0,3.38,414,156,...,50,CN,liminny,liminny,12134,3.866903,58aec90823ef726994a323fe,5b4ed29514f0765a8a844592,1,-0.91
1567,Combinaison sans manches pour femmes couleur u...,Sleeveless Solid Color Women Jumpsuit Ladies S...,8.00,7,EUR,20000,1,4.25,3127,1919,...,50,CN,Rell Mail,rellmail,16803,4.155032,56455b13b15aab129db58cb7,5c91a7ae7cfe8e4e64c36d97,0,-1.00
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,1,...,50,CN,modai,modai,31,3.774194,5d56b32c40defd78043d5af9,5eda07ab0e295c2097c36590,0,-2.00
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,8,...,50,CN,AISHOPPINGMALL,aishoppingmall,7023,4.235939,5a409cf87b584e7951b2e25f,5e857321f53c3d2d8f25e7ed,0,-1.00

In [36]:

negative_discounts = df[df['discount'] < 0]
print(len(negative_discounts))

548

In [37]:
df['is_on_sale'] = df['discount'] > 0

In [38]:
df.groupby("is_on_sale")["units_sold"].mean()

is_on_sale
False    4698.502717
True     4169.488169
Name: units_sold, dtype: float64

In [39]:
# პროდუქტები ფასდაკლების გარეშე უფრო იყიდება ვიდრე ნივთები ფასდაკლებით!!??

In [40]:
correlation = df['rating'].corr(df['units_sold'])
print(f"კორელაცია რეიტინგსა და გაყიდვებს შორის: {correlation}")

კორელაცია რეიტინგსა და გაყიდვებს შორის: 0.038371219776031786

In [41]:
df.groupby("is_on_sale")["rating"].mean()

is_on_sale
False    3.820014
True     3.825430
Name: rating, dtype: float64

In [42]:
# პროდუქტების 1/3-ს უარყოფითი ფასდაკლება (ფასნამატი) აქვს.
#ფასნამატის მქონე პროდუქტებს უფრო მეტი საშუალო გაყიდვები აქვთ.
#რეიტინგი და გაყიდვები ერთმანეთთან თითქმის არ არის კავშირში ($r \approx 0.038$).

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1539 entries, 0 to 1572
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   title                        1539 non-null   object
 1   title_orig                   1539 non-null   object
 2   price                        1539 non-null   float64
 3   retail_price                 1539 non-null   int64
 4   currency_buyer               1539 non-null   object
 5   units_sold                   1539 non-null   int64
 6   uses_ad_boosts               1539 non-null   int64
 7   rating                       1539 non-null   float64
 8   rating_count                 1539 non-null   int64
 9   rating_five_count            1539 non-null   int64
 10  rating_four_count            1539 non-null   int64
 11  rating_three_count           1539 non-null   int64
 12  rating_two_count             1539 non-null   int64
 13  rating_one_count             1539 non-null   int64
 14  badges_count                 1539 non-null   int64
 15  badge_local_product          1539 non-null   int64
 16  badge_product_quality        1539 non-null   int64
 17  badge_fast_shipping          1539 non-null   int64
 18  tags                         1539 non-null   object
 19  product_color                1539 non-null   object
 20  product_variation_size_id    1539 non-null   object
 21  product_variation_inventory  1539 non-null   int64
 22  shipping_option_name         1539 non-null   object
 23  shipping_option_price        1539 non-null   int64
 24  shipping_is_express          1539 non-null   int64
 25  countries_shipped_to         1539 non-null   int64
 26  inventory_total              1539 non-null   int64
 27  origin_country               1539 non-null   object
 28  merchant_title               1539 non-null   object
 29  merchant_name                1539 non-null   object
 30  merchant_rating_count        1539 non-null   int64
 31  merchant_rating              1539 non-null   float64
 32  merchant_id                  1539 non-null   object
 33  product_id                   1539 non-null   object
 34  has_urgency                  1539 non-null   int64
 35  discount                     1539 non-null   float64
 36  is_on_sale                   1539 non-null   bool
dtypes: bool(1), float64(4), int64(20), object(12)
memory usage: 446.4+ KB

In [44]:
df.to_csv("wish_products_cleaned.csv", index=False)

In [46]:
import os
os.getcwd()

'C:\\Users\\home\\Desktop\\ვებიზი\\Python\\მეოთხე ლექცია\\Python_Class'